---
apache_user: www-data
apache_group: www-data
apache_log: apache2

mysql_create_dir: ""

debian_keyring_path: /etc/apt/keyrings/
zabbix_gpg_key: "{{ debian_keyring_path }}/zabbix-official-repo.asc"
_zabbix_server_fping6location: /usr/bin/fping6
_zabbix_server_fpinglocation: /usr/bin/fping

_zabbix_server_package: "zabbix-server-{{ zabbix_server_database }}"
_zabbix_server_sql_scripts_package: "zabbix-sql-scripts"
_zabbix_server_install_recommends: true
