zabbix_valid_proxy_versions:
  # Debian
  "12":
    - 6.4
    - 6.0
  "11":
    - 6.4
    - 6.2
    - 6.0
  "10":
    - 6.4
    - 6.2
    - 6.0
  "22":
    - 6.4
    - 6.2
    - 6.0
  "20":
    - 6.4
    - 6.2
    - 6.0
  "18":
    - 6.4
    - 6.2
    - 6.0

_zabbix_proxy_pgsql_dependencies:
  - "{{ zabbix_proxy_install_database_client | ternary('postgresql-client', '') }}"
  - python3-psycopg2

_zabbix_proxy_mysql_dependencies:
  # Debian
  "12":
    - "{{ zabbix_proxy_install_database_client | ternary('default-mysql-client', '') }}"
    - "{{ zabbix_python_prefix }}-mysqldb"
  "11":
    - "{{ zabbix_proxy_install_database_client | ternary('default-mysql-client', '') }}"
    - "{{ zabbix_python_prefix }}-mysqldb"
  "10":
    - "{{ zabbix_proxy_install_database_client | ternary('default-mysql-client', '') }}"
    - "{{ zabbix_python_prefix }}-mysqldb"
  # Ubuntu
  "22":
    - "{{ zabbix_proxy_install_database_client | ternary('default-mysql-client', '') }}"
    - "{{ zabbix_python_prefix }}-mysqldb"
  "20":
    - "{{ zabbix_proxy_install_database_client | ternary('default-mysql-client', '') }}"
    - "{{ zabbix_python_prefix }}-mysqldb"
  "18":
    - "{{ zabbix_proxy_install_database_client | ternary('default-mysql-client', '') }}"
    - "{{ zabbix_python_prefix }}-mysqldb"

_zabbix_proxy_sqlite3_dependencies:
  - sqlite3

mysql_plugin:
  "18": mysql_native_password
  "10": mysql_native_password

debian_keyring_path: /etc/apt/keyrings/
zabbix_gpg_key: "{{ debian_keyring_path }}zabbix-repo.asc"
_zabbix_proxy_fping6location: /usr/bin/fping6
_zabbix_proxy_fpinglocation: /usr/bin/fping

_zabbix_proxy_package: "zabbix-proxy-{{ zabbix_proxy_database }}"
_zabbix_proxy_sql_scripts_package: "zabbix-sql-scripts"
