---
- name: Setting Web Server Facts
  ansible.builtin.set_fact:
    zabbix_web_user: "{{ zabbix_web_user if zabbix_web_user is defined else _apache_user }}"
    zabbix_web_group: "{{ zabbix_web_group if zabbix_web_group is defined else _apache_group }}"
  tags:
    - always

- name: "Apache | Installing Zabbix Apache Conf"
  package:
    name: "{{ _zabbix_web_apache_packages + _zabbix_web_apache_php_dependencies | default([]) }}"
    state: "{{ zabbix_web_package_state }}"
    update_cache: true
    disablerepo: "{{ zabbix_web_disable_repo | default(_zabbix_web_disable_repo | default(omit)) }}"
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: zabbix_apache_conf_install
  until: zabbix_apache_conf_install is succeeded
  become: true
  tags:
    - install
    - dependencies
    - database

- name: "Apache | Install apache vhost"
  ansible.builtin.template:
    src: apache_vhost.conf.j2
    dest: "{{ zabbix_web_vhost_location | default(_apache_vhost_location) }}"
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    mode: 0644
  when: zabbix_web_create_vhost
  become: true
  notify:
    - restart apache
  tags:
    - config

- name: "Apache | Enable Site (Debian Only)"
  ansible.builtin.file:
    src: "{{ zabbix_web_vhost_location | default(_apache_vhost_location) }}"
    dest: /etc/apache2/sites-enabled/zabbix.conf
    state: link
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    mode: 0644
  become: true
  when:
    - zabbix_web_create_vhost
    - ansible_facts['os_family'] == 'Debian'
  tags:
    - config
